export const HEROES_SUCCESS = "HEROES_SUCCESS";
export const HEROES_LOADING = "HEROES_LOADING";
export const HEROES_FETCHED = "HEROES_FETCHED"; 
export const INPUT_NAME_HERO = "INPUT_NAME_HERO";
export const HERO_SUCCESS = "HERO_SUCCESS"